// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf8batsx2kIwOUux7R1kyQqAd1B2li060',
    appId: '1:1029198856490:web:52c5fdc87900a9751c9e53',
    messagingSenderId: '1029198856490',
    projectId: 'ritesh-kumar-portfolio',
    authDomain: 'ritesh-kumar-portfolio.firebaseapp.com',
    storageBucket: 'ritesh-kumar-portfolio.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfUtugwV03uDIiau3tQCZvGL8-qkcjeew',
    appId: '1:1029198856490:android:f3611714bc25d86e1c9e53',
    messagingSenderId: '1029198856490',
    projectId: 'ritesh-kumar-portfolio',
    storageBucket: 'ritesh-kumar-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYFLPlHUZNf1UqrDIO1rnALdDUrBbBo54',
    appId: '1:1029198856490:ios:0b9468357461ac3f1c9e53',
    messagingSenderId: '1029198856490',
    projectId: 'ritesh-kumar-portfolio',
    storageBucket: 'ritesh-kumar-portfolio.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );
}
